% test_micro2atti
tic;
fprintf(1,'[%1.4f secs.] Load data...\n',toc);
load test_data;
fprintf(1,'[%1.4f secs.] Compute micro-model...\n',toc);
[lpar,lperp,~] = atti2micro( atti, gi, bi, ...
    'usef', false, 'tl', 1.0e-7, 'tu', 1-1.0e-7, ...
    'mlperp', 0, 'mu', 0, 'mask', mask, 'bth', 100 );
fprintf(1,'[%1.4f secs.] Compute the ODFs...\n',toc);
sh = micro2shodf( atti, gi, bi, lpar, lperp, [], ...
    'L', 8, 'lambda', 0.001, 'tl', 1.0e-7, 'tu', 1-1.0e-7, ...
    'mask', mask, 'optimal', false, 'bth', 100 );
fprintf(1,'[%1.4f secs.] Generating a synthetic att. signal...\n',toc);
atti2 = micro2atti(sh,lpar,lperp,[],gi,bi,'mask',mask,'bth',100);
fprintf(1,'[%1.4f secs.] Re-Compute micro-model over the synthetic att. signal...\n',toc);
[lpar,lperp,~] = atti2micro( atti2, gi, bi, ...
    'usef', false, 'tl', 1.0e-7, 'tu', 1-1.0e-7, ...
    'mlperp', 0, 'mu', 0, 'mask', mask, 'bth', 100 );
fprintf(1,'[%1.4f secs.] Re-compute the ODFs over the synthetic att. signal...\n',toc);
sh = micro2shodf( atti2, gi, bi, lpar, lperp, [], ...
    'L', 8, 'lambda', 0.001, 'tl', 1.0e-7, 'tu', 1-1.0e-7, ...
    'mask', mask, 'optimal', false, 'bth', 100 );
fprintf(1,'[%1.4f secs.] Generating a new synthetic att. signal...\n',toc);
atti3 = micro2atti(sh,lpar,lperp,[],gi,bi,'mask',mask,'bth',100);
fprintf(1,'[%1.4f secs.] All done. Plotting the results...\n',toc);
diffatt = 2*(atti2-atti3)./(atti2+atti3+1000*eps);

sl = [5,9,11,14];
close(figure(1));
hf = figure(1);
G = size(atti,4);
for g=1:8:G
    R=1;C=4;
    r=1; c=1; subplot('Position',[(c-1)/C,(r-1)/R+0.05/R,3/C,0.9/R]);
    IMG = [ ...
        atti(:,:,sl(1),g)', atti2(:,:,sl(1),g)', atti3(:,:,sl(1),g)'; ...
        atti(:,:,sl(2),g)', atti2(:,:,sl(2),g)', atti3(:,:,sl(2),g)'; ...
        atti(:,:,sl(3),g)', atti2(:,:,sl(3),g)', atti3(:,:,sl(3),g)'; ...
        atti(:,:,sl(4),g)', atti2(:,:,sl(4),g)', atti3(:,:,sl(4),g)'  ];
    imshow(IMG,[0,1]); colormap(psychedelia(512)); colorbar;
    title('atti (orig), atti2 (synth), atti3 (synth 2)');
    r=1; c=4; subplot('Position',[(c-1)/C,(r-1)/R+0.05/R,1/C,0.9/R]);
    IMG = [ ...
        diffatt(:,:,sl(1),g)'; ...
        diffatt(:,:,sl(2),g)'; ...
        diffatt(:,:,sl(3),g)'; ...
        diffatt(:,:,sl(4),g)';     ];
    imshow(IMG,[-0.1,0.1]); colormap(psychedelia(512)); colorbar;
    title('atti2-atti3 (relative)');
    set(hf,'Name',sprintf('[Channel: %d / %d]',g,G),'Position',[10,10,800,600]);
    pause(0.2);
end
