% Logo
% Plot the L-shaped membrane logo with MATLAB(R) lighting.

% Copyright 1984-2007 The MathWorks, Inc.


z     = 40*membrane(1,400);
x     = (1:size(z,1))/16;
y     = (1:size(z,2))/16;
[x,y] = meshgrid(x,y);
IMG   = permute(imread('colorcode.jpg'),[1,2,3]);
IMG   = IMG(:,end:-1:1,:);
W     = size(IMG,1);
H     = size(IMG,2);
IMG   = imrotate(IMG,40);
W2    = size(IMG,1);
H2    = size(IMG,2);
IMG   = IMG( round(W2/2)+round(0.75*(-W/2+1:W/2)),round(H2/2)+round(0.75*(-H/2+1:H/2)), : );
IMG   = imresize(IMG,size(z));

logoFig = figure('Color',[1 1 1]);
logoax = axes('CameraPosition', [-193.4013 -265.1546  220.4819],...
    'CameraTarget',[26 26 10], ...
    'CameraUpVector',[0 0 1], ...
    'CameraViewAngle',9.5, ...
    'DataAspectRatio', [1 1 .9],...
    'Position',[0 0 1 1], ...
    'Visible','off', ...
    'XLim',[1 51], ...
    'YLim',[1 51], ...
    'ZLim',[-13 40], ...
    'parent',logoFig);
s = surface(x,y,z,IMG,...
    'EdgeColor','none', ...
    'FaceLighting','non', ...
    'AmbientStrength',0.3, ...
    'DiffuseStrength',0.6, ... 
    'Clipping','off',...
    'BackFaceLighting','lit', ...
    'SpecularStrength',1, ...
    'SpecularColorReflectance',1, ...
    'SpecularExponent',7, ...
    'Tag','TheMathWorksLogo', ...
    'parent',logoax);
l1 = light('Position',[40 100 20], ...
    'Style','local', ...
    'Color',[0 0.8 0.8], ...
    'parent',logoax);
l2 = light('Position',[.5 -1 .4], ...
    'Color',[0.8 0.8 0], ...
    'parent',logoax);

% Have logo use camera pan and zoom since limits pan and zoom looks strange
% with CameraTarget set
z = zoom(logoFig);
z.setAxes3DPanAndZoomStyle(logoax,'camera');